name: Build and Deploy Workflow to S3
on:
  push: 
    branches: ["main"]
jobs: 
  build-and-deploy:
    name: Build and Deploy to S3
    runs-on: ubuntu-latest
    env:
      BUCKET: michaelhyunn.com
      SECOND_BUCKET: www.michaelhyunn.com
      REGION: us-east-1
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: ${{ env.REGION }}
    - name: Install Dependencies
      run: |
        node --version
        npm ci --production
    - name: Build App
      run: |
        npm run build
    - name: Copy files to S3
      run: |
        aws s3 sync ./build s3://${{ env.BUCKET }}
        aws s3 sync ./build s3://${{ env.SECOND_BUCKET }}
  
  